==== From 01/2020:
Based in part on: https://github.com/dmacvicar/terraform-provider-libvirt#downloading

.Make libvirt provider available to the current users:
* (for leap 15.1): `zypper addrepo https://download.opensuse.org/repositories/systemsmanagement:terraform/openSUSE_Leap_15.1/systemsmanagement:terraform.repo`
* `zypper refresh`
* `sudo zypper install terraform-provider-libvirt`
* `cp -p /usr/bin/terraform-provider-libvirt ~/.terraform.d/plugins/`
* Verify the provider is available: `terraform init`
** Should complete without error and include the phrase:
----
Initializing provider plugins...

Terraform has been successfully initialized!
----

.Test the libvirt provider:
* Create the libvirt.tf file:
----
cat <<EOF>libvirt.tf
provider "libvirt" {
    uri = "qemu:///system"
}
EOF
----

* Create the terraform_test.tf test file:
----
cat <<EOF>terraform_test.tf
resource "libvirt_domain" "terraform_test" {
  name = "terraform_test"
}
EOF
----

* Verify the terraform plan: `terraform plan`
* Apply the terraform plan: `terraform apply`
* Remove the test: `terraform destroy`




=== To deploy to a remote instance of qemu:
* Ensure the user on the remote node is in the libvirt group on that node
* Enure the user on the local node can ssh to the remote node without a password
* Run ssh-agent and add the specific key that allows passwordless ssh to the remote node
* Declare the libvirt daemon on the remote node in the appopriate .tf file:
----
provider "libvirt" {
  uri = "qemu+ssh://admin@infra1.caaspv4.com/system"
}
----
or
* In a variables file:
----
libvirt_uri = "qemu+ssh://admin@infra1.caaspv4.com/system"
----
* In the infrastructure file:
----
provider "libvirt" {
  uri = var.libvirt_uri
}
----

=== To copy files and directories to an instance upon creation
* NOTE: Terraform strongly discourages using provisioners unless there are no other options
* From: https://www.terraform.io/docs/provisioners/file.html
* Can copy individual files, or directories, or specific content into a file
----
  # Copies the myapp.conf file to /etc/myapp.conf
  provisioner "file" {
    source      = "conf/myapp.conf"
    destination = "/etc/myapp.conf"
  }
----  

CAUTION: Uses rysnc behavoir which varies based on a directory specified with a trailing slash. 

----
  # Copies the configs.d folder to /etc/configs.d
  provisioner "file" {
    source      = "conf/configs.d"
    destination = "/etc"
  }

  # Copies all files and folders in apps/app1 to D:/IIS/webapp1
  provisioner "file" {
    source      = "apps/app1/"
    destination = "D:/IIS/webapp1"
  }
}
----

==== Populating the authorized_keys file
----
authorized_keys = [
"<public key>", "<public key>", "<public key>"
]




=== These are random, now basically unhelpful notes from 09/2019
* After creating a TF instance:
** Make changes
** rm -rf /var/lib/cloud/*
** poweroff VM
** Copy the deployed image to somewhere persistent
** terraform destroy

* Launch a new TF instance with the new image
** In the cloud init file add two lines to the "bootcmd:" expresion:
  - sed -i 's/eth1/eth0/' /etc/udev/rules.d/70-persistent-net.rules
  - udevadm trigger
** Set up networking


// vim: set syntax=asciidoc:
