.Requires Kubergrunt to gather the OIDC information for the tokens Kubernetes will create
* https://github.com/gruntwork-io/kubergrunt

.AWS profile has been disabled in favor of passing credentials through environmental variables
* Set the variables AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_DEFAULT_REGION:
----
export AWS_ACCESS_KEY_ID=""
export AWS_SECRET_ACCESS_KEY=""
export AWS_DEFAULT_REGION=""
----
* Alternately, use the aws cli to create a profile, uncomment the profile section in provider.tf, and refer to the profile in variables.tf

## This environment uses an S3 backend to maintain state files

.If needed, use aws cli to create the bucket:

* Set the environmental variables below:
----
UNIQUE_BUCKET_NAME=""
REGION=""
----
----
aws s3api create-bucket --bucket ${UNIQUE_BUCKET_NAME} --region ${REGION} --create-bucket-configuration LocationConstraint=${REGION}
----

* Use the following command to list all buckets you have access to:
----
aws s3api list-buckets --query "Buckets[].Name" --output table --no-cli-pager
----

## The environment must be initialized to save this specific state configuration before running `terraform apply`

NOTE: This design allows for creating and maintaining different clusters with the same code. Each cluster must have a different name.

* Set the environmental variables below:
----
CLUSTER_NAME=""
UNIQUE_BUCKET_NAME=""
REGION=""
----
----
rm .terraform/terraform.tfstate; terraform init -backend-config=key="${CLUSTER_NAME}-terraform.tfstate" -backend-config=bucket="${UNIQUE_BUCKET_NAME}" -backend-config=region="${REGION}"
----

----
terraform apply -var=cluster_name1=${CLUSTER_NAME} -var=region=${REGION}
----

* When finished, destroy the cluster:
----
terraform destroy -var=cluster_name1=${CLUSTER_NAME} -var=region=${REGION}
----

IMPORTANT: Switching between clusters requires setting the `CLUSTER_NAME` variable and running `terraform init`, as shown above, before running `terraform apply` or `terraform destroy`
