.AWS profile has been disabled in favor of passing credentials through environmental variables
* Set the variables AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_DEFAULT_REGION:
----
export AWS_ACCESS_KEY_ID=""
export AWS_SECRET_ACCESS_KEY=""
export AWS_DEFAULT_REGION=""
----
* Alternately, use the aws cli to create a profile, uncomment the profile section in provider.tf, and refer to the profile in variables.tf

## This environment uses an S3 backend to maintain state files

* If needed, use aws cli to create the bucket:
----
REGION=
UNIQUE_BUCKET_NAME=
----
----
aws s3api create-bucket --bucket ${UNIQUE_BUCKET_NAME} --region ${REGION} --create-bucket-configuration LocationConstraint=${REGION}
----

## The environment must be initialized to save this specific state before applying a configuration:

NOTE: This design allows for using a different cluster name with every terraform apply and destroy to keep clusters separate.

----
CLUSTER_NAME=
----
----
terraform init -backend-config=key=${CLUSTER_NAME}-terraform.tfstate
----

----
terraform apply -var=cluster_name1=${CLUSTER_NAME}
----

* When finished, destroy the cluster:
----
terraform destroy -var=cluster_name1=${CLUSTER_NAME}
----

IMPORTANT: Switching between clusters requires setting the `CLUSTER_NAME` varialbe and running `terraform init`, as shown above, before running `terraform apply` or `terraform destroy`
